from typing import Literal


PAYMENT_METHODS = Literal['BITCOIN', 'BITCOINCASH', 'BNBCRYPTOBOT', 'BNBSMARTCHAIN', 'BTCCRYPTOBOT', 'CARDKZTP2P', 'CARDRUBP2P', 'CRYSTALPAY', 'DASH', 'DOGECOIN', 'ETHCRYPTOBOT', 'ETHEREUM', 'LITECOIN', 'LTCCRYPTOBOT', 'LZTMARKET', 
                          'MONERO', 'POLYGON', 'SBERPAYP2P', 'SBPP2P', 'TEST', 'TONCOIN', 'TONCRYPTOBOT', 'TRON', 'USDCTRC', 'USDTBEP', 'USDTCRYPTOBOT', 'USDTTRC']